import type { Metadata, Viewport } from 'next';
import { AnalyticsWithOptOut } from '@/components/AnalyticsWithOptOut';
import { SpeedInsightsWithOptOut } from '@/components/SpeedInsightsWithOptOut';
import { IBM_Plex_Mono, IBM_Plex_Sans } from 'next/font/google';
import { SessionProvider } from '@/providers/SessionProvider';
import { SWRProvider } from '@/providers/SWRProvider';
import { ScrollToTop } from '@/components/ScrollToTop';
import '@/app/globals.css';

const ibmPlexMono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-ibm-plex-mono',
  display: 'swap',
});

// Proportional sibling of Plex Mono — used for conversational/long-form text
// (chat, check-in prose) so the human parts read warmer than the mono UI chrome.
const ibmPlexSans = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-ibm-plex-sans',
  display: 'swap',
});

// viewport-fit=cover so env(safe-area-inset-*) resolves on notched iPhones,
// especially in standalone (home-screen) mode.
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
};

// Absolute base for OG/Twitter URLs. Vercel exposes the deployment host but
// without a scheme, so preview builds unfurl against themselves and only
// production falls back to the canonical domain.
const siteUrl = process.env.NEXT_PUBLIC_SITE_URL
  ? process.env.NEXT_PUBLIC_SITE_URL
  : process.env.VERCEL_URL
    ? `https://${process.env.VERCEL_URL}`
    : 'https://logbook.fit';

const TITLE = 'Logbook.fit · Your quietest client is your next cancellation';
const DESCRIPTION =
  'The retention-first platform for independent coaches. Logbook.fit ranks your clients by who needs you today, so you catch the fade before it becomes a refund.';

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: 'LogBook.fit',
  description: DESCRIPTION,
  // Nearly all waitlist traffic arrives through a shared link, so an unfurl
  // that renders as a bare URL leaks conversions on every channel at once.
  // The card itself is generated by app/opengraph-image.tsx.
  openGraph: {
    type: 'website',
    siteName: 'Logbook.fit',
    title: TITLE,
    description: DESCRIPTION,
    url: siteUrl,
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
  },
  appleWebApp: {
    capable: true,
    title: 'Logbook',
    statusBarStyle: 'default',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${ibmPlexMono.variable} ${ibmPlexSans.variable}`}>
      <body>
        <SessionProvider>
          <SWRProvider>
              <ScrollToTop />
              {children}
          </SWRProvider>
        </SessionProvider>
        <AnalyticsWithOptOut />
        <SpeedInsightsWithOptOut />
      </body>
    </html>
  );
}
